---

# Site-Wide Content
# -----------------

contact:
  - title: 'Let’s Build Something Together!'
    content: |
      <strong>We want to hear all about your software ideas.</strong>
      Fill out our
      <a href="/contact/">contact form</a>,
      join our
      <a href="http://friends.oddbird.net">public Slack chat</a>,
      or tweet
      <a href="http://twitter.com/oddbird">@oddbird</a>
      to start the conversation.


# Future Talks
# ------------

events:

  - venue: 'Front-End Camp'
    url: 'http://chicagocamps.org/events/2017/front-end-camp/'
    date: ['6', '3', '2017']
    adr:
      city: 'Chicago'
      state: 'IL'
    who:
      - author: 'stacy'
        title: 'The Great State of Design with CSS Grid Layout & Friends'


# Past Talks
# ----------

events_past:

  - venue: 'WordPress Naperville'
    url: 'https://www.meetup.com/WordPress-Naperville/events/236903886/'
    date: ['3', '21', '2017']
    adr:
      city: 'Naperville'
      state: 'IL'
    who:
      - author: 'stacy'
        title: 'From Scratch to Launch: Front-end Theme Building'

  - venue: 'WordPress Naperville'
    url: 'https://www.meetup.com/WordPress-Naperville/events/236903879/'
    date: ['2', '21', '2017']
    adr:
      city: 'Naperville'
      state: 'IL'
    who:
      - author: 'stacy'
        title: 'From Scratch to Launch: Design Phase'
        slides: 'https://www.slideshare.net/Funstacy/from-scratch-to-launch-2-design-phase'

  - venue: 'UVA Scholars’ Lab'
    url: 'http://cal.lib.virginia.edu/event/3088981'
    date: ['01', '23', '2017']
    adr:
      city: 'Charlottesville'
      state: 'VA'
    who:
      - author: 'miriam'
        title: 'A Practical Guide to Losing Control'

  - venue: 'WordPress Naperville'
    url: 'https://www.meetup.com/WordPress-Naperville/events/236485707/'
    date: ['1', '17', '2017']
    adr:
      city: 'Naperville'
      state: 'IL'
    who:
      - author: 'stacy'
        title: 'From Scratch to Launch: Planning Phase'
        slides: 'https://www.slideshare.net/Funstacy/from-scratch-to-launch-series-part1-planning-phase'

  - venue: 'Gotham Sass'
    url: 'https://www.meetup.com/gothamsass/events/235946893/'
    date: ['01', '12', '2017']
    adr:
      city: 'New York'
      state: 'NY'
    who:
      - author: 'miriam'
        title: 'Code Patterns for Pattern Making'

  - venue: 'CSSDay.io'
    url: 'http://cssday.io/'
    date: ['12', '03', '2016']
    adr:
      city: 'Chandler'
      state: 'AZ'
    who:
      - author: 'miriam'
        title: 'Code Patterns for Pattern-Making'
        slides: 'http://oddbooksapp.com/book/pattern-making'
      - author: 'stacy'
        title: 'The Great State of Design (with CSS Grid Layout and Friends)'
        slides: 'https://www.slideshare.net/Funstacy/the-great-state-of-design-with-css-grid-layout-and-friends'

  - venue: 'Plone Digital Experience Conference'
    url: 'http://2016.ploneconf.org/'
    date: ['10', '20', '2016']
    adr:
      city: 'Boston'
      state: 'MA'
    who:
      - author: 'david'
        title: 'Greater than the sum of the parts: Lessons from integrating Pyramid, React, and Plone'

  - venue: 'CSSConf 2016'
    url: 'http://2016.cascadiafest.org/'
    date: ['09', '26', '2016']
    adr:
      city: 'Boston'
      state: 'MA'
    who:
      - author: 'miriam'
        title: 'Sass Map Magic'

  - venue: 'CascadiaFest'
    url: 'http://2016.cascadiafest.org/'
    date: ['08', '03', '2016']
    who:
      - author: 'miriam'
        title: 'Code Patterns for Pattern-Making'
        slides: 'http://oddbooksapp.com/book/pattern-making'

  - venue: 'CSS Summit'
    url: 'http://environmentsforhumans.com/2016/css-summit/'
    date: ['07', '26', '2016']
    who:
      - author: 'miriam'
        title: 'Code Patterns for Pattern-Making'
        slides: 'http://oddbooksapp.com/book/pattern-making'

  - venue: 'DublinCSS'
    url: 'http://www.meetup.com/DublinCSS/events/230011902/'
    date: ['05', '19', '2016']
    who:
      - author: 'miriam'
        title: 'Pattern-Making in Sass'
        slides: 'http://oddbooksapp.com/book/sass-patterns'

  - venue: 'WordCamp Chicago'
    url: 'https://2016.chicago.wordcamp.org/'
    date: ['05', '01', '2016']
    who:
      - author: 'stacy'
        title: 'Curing Design Complacency'
        slides: 'http://www.slideshare.net/Funstacy/curing-design-complacency-61550889'

  - venue: 'UX Camp'
    url: 'http://chicagocamps.org/events/2016/ux-camp/'
    date: ['04', '30', '2016']
    who:
      - author: 'stacy'
        title: 'Curing Design Complacency'
        slides: 'http://www.slideshare.net/Funstacy/curing-design-complacency-61550889'

  - venue: 'Clarity Conference'
    url: 'http://clarityconf.com/'
    date: ['03', '31', '2016']
    who:
      - author: 'miriam'
        title: 'Code Patterns for Pattern-Making'
        slides: 'http://oddbooksapp.com/book/pattern-making'

  - venue: 'Parent Programming'
    url: 'http://parentprogramming.libsyn.com/'
    date: ['03', '16', '2016']
    who:
      - author: 'stacy'
        title: 'A conversation with Kevin Lamping'
        audio: 'http://parentprogramming.libsyn.com/stacy-kvernmo'

  - venue: 'Shop Talk Show'
    url: 'http://shoptalkshow.com/'
    date: ['12', '16', '2015']
    who:
      - author: 'stacy'
        title: 'A conversation with Chris Coyier and Dave Rupert'
        audio: 'http://shoptalkshow.com/episodes/197-with-stacy-kvernmo/'

  - venue: 'SassConf 2015'
    url: 'http://sassconf.com'
    date: ['11', '11', '2015']
    who:
      - author: 'stacy'
        title: 'Code Reviews: Turn Humiliation into Greatness'
        slides: 'http://www.slideshare.net/Funstacy/sass-code-reviews-how-one-code-review-changed-my-life-sassconf2015'
      - author: 'miriam'
        title: 'User UnFriendly [Notes Towards a Queer Web]'
        slides: 'http://oddbooksapp.com/book/user-unfriendly'

  - venue: 'CSS Dev Conf'
    url: 'http://2015.cssdevconf.com'
    date: ['10', '27', '2015']
    who:
      - author: 'stacy'
        title: 'No Pain No Gain; CSS Code Reviews'
        slides: 'http://www.slideshare.net/Funstacy/no-pain-no-gain-css-code-reviews-ftw'

  - venue: 'Sass Bites'
    url: 'https://www.youtube.com/user/sassbites'
    date: ['09', '24', '2015']
    who:
      - author: 'stacy'
        title: 'Sass Bites #91'
        video: 'https://www.youtube.com/watch?v=9uTZJJ-DQQM'

  - venue: 'Frontend Conference Zurich'
    url: 'http://frontendconf.ch'
    date: ['08', '28', '2015']
    who:
      - author: 'miriam'
        title: 'Sassy Toolkits'
        slides: 'http://oddbooksapp.com/book/sassy-toolkits'
        video: 'https://www.youtube.com/watch?v=9w0pgUTYy5k'

  - venue: 'CSS Summit'
    url: 'http://environmentsforhumans.com/2015/css-summit/'
    date: ['07', '07', '2015']
    who:
      - author: 'miriam'
        title: 'Sass Map Magic'
        url: 'http://oddbooksapp.com/book/sass-map-magic'

  - venue: 'WordCamp Denver'
    url: 'http://denver.wordcamp.org/2015/'
    date: ['06', '13', '2015']
    who:
      - author: 'miriam'
        title: 'Sassy Toolkits'
        slides: 'http://oddbooksapp.com/book/sassy-toolkits'

  - venue: 'Future Insights Live'
    date: ['06', '02', '2015']
    who:
      - author: 'miriam'
        title: 'Sass Map Magic'
        url: 'http://oddbooksapp.com/book/sass-map-magic'

  - venue: 'WordPress Naperville'
    url: 'http://www.meetup.com/WordPress-Naperville'
    date: ['02', '16', '2015']
    who:
      - author: 'stacy'
        title: 'It is a Mobile-First World'

  - venue: 'WordPress Naperville'
    url: 'http://www.meetup.com/WordPress-Naperville'
    date: ['01', '20', '2015']
    who:
      - author: 'stacy'
        title: 'What NOT to Do With WordPress'

  - venue: 'SassConf 2014 [Unconference Day]'
    url: 'http://sassconf.com'
    date: ['10', '02', '2014']
    who:
      - author: 'miriam'
        title: 'Sass Map Magic'
        url: 'http://oddbooksapp.com/book/sass-map-magic'

  - venue: 'BlendConf'
    url: 'http://www.blendconf.com/'
    date: ['09', '12', '2014']
    who:
      - author: 'miriam'
        talk: 'Magic with Sass Maps'
        video: 'http://teamtreehouse.com/library/sass-map-magic'
      - author: 'claudina'
        title: 'Getting to know Sass'

  - venue: 'WordCamp Milwaukee'
    url: 'https://2014.milwaukee.wordcamp.org'
    date: ['07', '27', '2014']
    who:
      - author: 'stacy'
        title: 'Evolving the Design Process'
        slides: 'http://www.slideshare.net/Funstacy/design-processwcmke'

  - venue: 'WordCamp Chicago'
    url: 'https://2014.chicago.wordcamp.org'
    date: ['06', '15', '2014']
    who:
      - author: 'stacy'
        title: 'Evolving the Design Process'
        slides: 'http://www.slideshare.net/Funstacy/exploring-the-design-process-wcchi'
        video: 'http://wordpress.tv/2014/07/05/stacy-kvernmo-exploring-the-design-process/'

  - venue: 'ELO Conference'
    url: 'http://conference.eliterature.org/'
    date: ['06', '19', '2014']
    who:
      - author: 'miriam'
        title: 'The Post-Obsolete Book'

  - venue: 'Sass Bites'
    url: 'https://www.youtube.com/user/sassbites'
    date: ['05', '13', '2014']
    who:
      - author: 'claudina'
        title: 'Sass Bites #37'
        video: 'https://www.youtube.com/watch?v=BtWaFDpyDCI'

  - venue: 'Bmore Sass'
    url: 'http://bmore-sass.com/'
    date: ['04', '24', '2014']
    who:
      - author: 'miriam'
        title: 'Your Own Damn [Susy] System'
        slides: 'http://miriamsuzanne.com/pres/susy2/'
        video: 'http://vimeo.com/miriamsuzanne/susy-2-system'

  - venue: 'Camp Sass'
    url: 'http://campsass.com/2014/'
    date: ['04', '19', '2014']
    who:
      - author: 'miriam'
        title: 'Show Your Work <i>&</i> Share Your Toys'
        slides: 'http://miriamsuzanne.com/pres/show-yr-work/index.html'

  - venue: 'The Mixin'
    url: 'https://themixin.eventbrite.com/'
    date: ['04', '16', '2014']
    who:
      - author: 'miriam'
        title: 'Your Own Damn [Susy] System'
        slides: 'http://miriamsuzanne.com/pres/susy2/'

  - venue: 'PyCon'
    url: 'https://us.pycon.org/2014/'
    date: ['04', '13', '2014']
    who:
      - author: 'carl'
        title: 'Set Your Code Free'
        slides: '/set-your-code-free-preso/'
        video: 'http://pyvideo.org/video/2637/set-your-code-free-releasing-and-maintaining-an'

  - venue: 'Sass Bites'
    url: 'https://www.youtube.com/user/sassbites'
    date: ['03', '13', '2014']
    who:
      - author: 'miriam'
        title: 'Susy Grids 2.0'
        video: 'https://www.youtube.com/watch?v=m7k-vBzebPg'

  - venue: 'ConFoo'
    url: 'http://confoo.ca/'
    date: ['02', '28', '2014']
    who:
      - author: 'carl'
        title: 'Python Testing Tools'
        slides: '/python-testing-tools-preso/'

  - venue: 'ConFoo'
    url: 'http://confoo.ca/'
    date: ['02', '27', '2014']
    who:
      - author: 'carl'
        title: 'Advanced Python'
        slides: '/advanced-python-preso/'

  - venue: 'NYCSass Meetup'
    url: 'http://www.meetup.com/nyc-sass/events/146898452/'
    date: ['11', '19', '2013']
    who:
      - author: 'miriam'
        title: 'Organizing Sass Partials'
        slides: 'http://miriamsuzanne.com/pres/sass-partials/'

  - venue: 'SassConf 2013'
    url: 'http://sassconf.com/2013/'
    date: ['10', '12', '2013']
    who:
      - author: 'miriam'
        title: 'Show Your Work & Share Your Toys'
        slides: 'http://miriamsuzanne.com/pres/show-yr-work/'
        video: 'https://vimeo.com/channels/sassconf2013/86306775'

  - venue: 'Brakhage Center Media Arts'
    url: 'http://www.colorado.edu/brakhagecenter/2013/08/10/bc-luncheon-series-welcomes-eric-meyer-october-7th'
    date: ['10', '07', '2013']
    who:
      - author: 'miriam'
        title: 'Art is for People'
        slides: 'http://miriamsuzanne.com/art-is-for-people/'

  - venue: 'WordPress Naperville'
    url: 'http://www.meetup.com/WordPress-Naperville'
    date: ['09', '17', '2013']
    who:
      - author: 'stacy'
        title: 'A development site. Why do I need one?'

  - venue: 'PyCon'
    url: 'https://us.pycon.org/2013/'
    date: ['03', '16', '2013']
    who:
      - author: 'carl'
        title: 'Getting Started with Automated Testing'
        slides: '/start-testing-preso/'
        video: 'http://pyvideo.org/video/1674/getting-started-with-automated-testing'

  - venue: 'DjangoCon'
    url: 'https://djangocon.us'
    date: ['09', '07', '2016']
    who:
      - author: 'carl'
        title: 'Taming dependencies with pip'
        video: 'http://pyvideo.org/video/69/djangocon-2011--taming-dependencies-with-pip'

  - venue: 'PyCon'
    url: 'https://us.pycon.org/2012/'
    date: ['03', '10', '2012']
    who:
      - author: 'carl'
        title: 'Testing and Django'
        video: 'http://pyvideo.org/video/699/testing-and-django'

  - venue: 'PyCon'
    url: 'https://us.pycon.org/2011/'
    date: ['03', '12', '2011']
    who:
      - author: 'carl'
        title: "Reverse-engineering Ian Bicking's brain: inside pip and virtualenv"
        video: 'http://pyvideo.org/video/389/pycon-2011--reverse-engineering-ian-bicking--39-s'


# Navigation
# ----------

nav:
  - text: 'work'
    url: '/work/'
  - text: 'open-source'
    display_text: 'open source'
    url: '/open-source/'
  - text: 'blog'
    display_text: 'articles'
    url: '/blog/'
  - text: 'about'
    display_text: 'about us'
    subnav:
      - text: 'birds'
        display_text: 'meet the birds'
        url: '/birds/'
      - text: 'speaking'
        display_text: 'public speaking'
        url: '/speaking/'
      - text: 'community'
        url: '/community/'
      - text: 'contact'
        display_text: 'contact us'
        url: '/contact/'


# Site Settings
# -------------

copyright: '2009–2017'
email: 'birds@oddbird.net'

location: 'blog'
author: 'oddbird'
comments: false


# rstBlog Setup
# -------------

active_modules: [
  jinja_macros,
  typogrify,
  images,
  denormalize_config,
  tags,
  extended_tags,
  blog,
  author,
  pages,
  wrap,
  hashedassets,
  urls
  ]
programs:
  '*.rst': 'rst'
  '*.jpg': 'image'
  '*.jpeg': 'image'
  '*.png': 'image'
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/assets.json
rst_writer: html5writer
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  blog:
    index_url: /blog/
    per_page: 10
