---


# Navigation
# ----------

nav:
  - text: 'work'
    subnav:
      - text: 'case-studies'
        display_text: 'clients & case studies'
        url: '/work/'
      - text: 'open-source'
        display_text: 'open source tools'
        url: '/open-source/'
  - text: 'services'
    subnav:
      - text: 'development'
        display_text: 'app design & development'
        url: '/services/'
      - text: 'planning'
        display_text: 'research & concepting'
        url: '/services/planning/'
      - text: 'design-systems'
        display_text: 'integrated design systems'
        url: '/services/design-systems/'
      - text: 'speaking'
        display_text: 'speaking & training'
        url: '/services/speaking/'
  - text: 'about'
    subnav:
      - text: 'birds'
        display_text: 'meet the birds'
        url: '/birds/'
      - text: 'community'
        url: '/community/'
      - text: 'now hiring'
        url: '/jobs/'
  - text: 'blog'
    display_text: 'articles'
    url: '/blog/'


# Site Settings
# -------------

copyright: '2009–2018'
email: 'birds@oddbird.net'

author: oddbird
comments: false


# rstBlog Setup
# -------------

active_modules: [
  jinja_macros,
  current,
  typogrify,
  rst,
  images,
  denormalize_config,
  tags,
  blog,
  author,
  pages,
  wrap,
  hashedassets,
  urls
  ]
programs:
  '*.rst': 'rst'
  '*.jpg': 'image'
  '*.jpeg': 'image'
  '*.png': 'image'
canonical_url: http://oddbird.net/
template_path: ../templates
asset_map_path: static/assets.json
rst_writer: html5writer
smart_quotes: true
ignore_files: ['.*', '_*', 'config*.yml', 'Makefile', 'README', '*.conf', '*~']
modules:
  blog:
    index_url: /blog/
    per_page: 10
